# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Joonhyun Jeong
title: AI Research Engineer
email: doublejtoh@naver.com / joonhyun.jeong@navercorp.com / joonhyun.jeong@mli.kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://gamer691.blogspot.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  doublejtoh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: bestdeveloper691
# flickr_username: jekyll
instagram_username: bestdeveloper691
linkedin_username: doublejtoh
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Best Developer Enjoying Life with AI. \\
  My Research Interests are
    - Computer Vision
    - Multi-Modal Vision-Language Models
    - Object Detection
    - Model Compression
    - Neural Architecture Search
    - Data Augmentation

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Codigm (Goorm)
        caption: Mar 2018 - Jun 2018
        link: https://goorm.co/
        description: | # this will include new lines to allow paragraphs
          Web Front & Backend Engineer / Intern
      - layout: right
        title: NAVER CLOVA
        caption: Sep 2019 - Feb 2020
        link: https://clova.ai/ko
        description: | # this will include new lines to allow paragraphs
          AI Model Research & Develop for Face Detection task / Intern (Face team)
      - layout: right
        title: NAVER CLOVA
        caption: May 2020 - Current
        link: https://clova.ai/ko
        description: |
          AI Research Engineer / Full-Timer in Image Vision team under the supervision of Youngjoon Yoo.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Kyung-Hee University
        sub_title: Bachelor Degree, Department of Computer Science and Engineering
        caption: Mar 2015 - Feb 2019
        # quote: >
        #   Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification
      - layout: top-right
        title: Kyung-Hee University
        sub_title: Department of Computer Science and Engineering
        # sub_title: Bachelor Degree, Department of Computer Science and Engineering
        caption: Mar 2019 - Aug 2019
        quote: >
          Machine Learning and Visual Computing Laboratory (MLVC) Lab under the supervision of Prof. Sung-Ho Bae.
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification
      - layout: top-right
        title: Korea Advanced Institute of Science and Technology (KAIST)
        sub_title: Master Degree, Kim Jaechul Graduate School of AI (GSAI)
        caption: Sep 2022 - Current
        quote: >
          Machine Learning and Intelligence LAB (MLI) Lab under the supervision of Prof. Eunho Yang.
        # description: | # this will include new lines to allow paragraphs
        #   Description of qualification
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-right
        title: "Playing the Fool: Jailbreaking LLMs and Multimodal LLMs with Out-of-Distribution Strategy"
        sub_title: CVPR 2025
        caption: <b>Joonhyun Jeong</b>, Seyun Bae, Yeonsung Jung, Jaeryong Hwang, Eunho Yang
      - layout: top-right
        title: "ZIM: Zero-Shot Image Matting for Anything"
        sub_title: Arxiv preprint 2025
        caption: Beomyoung Kim, Chanyong Shin, <b>Joonhyun Jeong</b>, Hyungsik Jung, Se-Yun Lee, Sewhan Chun, Dong-Hyun Hwang, Joonsang Yu
      - layout: top-right
        title: "Hijacking Context in Large Multi-modal Models"
        sub_title: ICLRW 2024 (R2-FM Workshop)
        caption: <b>Joonhyun Jeong</b>
        link: https://arxiv.org/abs/2312.07553
        link_text: >
          [Paper]
      - layout: top-right
        title: "ProxyDet: Synthesizing Proxy Novel Classes via Classwise Mixup for Open Vocabulary Object Detection"
        sub_title: AAAI 2024
        caption: <b>Joonhyun Jeong</b>, Geondo Park, Jayeon Yoo, Hyungsik Jung, Heesu Kim
        link: https://arxiv.org/abs/2312.07266
        link_text: >
          [Paper]
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/clovaai/ProxyDet
      - layout: top-right
        title: "EResFD: Rediscovery of the Effectiveness of Standard Convolution for Lightweight Face Detection"
        sub_title: WACV 2024
        caption: <b>Joonhyun Jeong</b>, Beomyoung Kim, Joonsang Yu, Youngjoon Yoo
        link: https://arxiv.org/abs/2204.01209
        link_text: >
          [Paper]
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/clovaai/EResFD
      - layout: top-right
        title: "GeNAS: Neural Architecture Search with Better Generalization"
        sub_title: IJCAI 2023
        caption: <b>Joonhyun Jeong</b>, Joonsang Yu, Geondo Park, Dongyoon Han, Youngjoon Yoo
        link: https://www.ijcai.org/proceedings/2023/0101.pdf
        link_text: >
          [Paper]
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/clovaai/GeNAS
      - layout: top-right
        title: "The Devil is in the Points: Weakly Semi-Supervised Instance Segmentation via Point-Guided Mask Representation"
        sub_title: CVPR 2023
        caption: Beomyoung Kim, <b>Joonhyun Jeong</b>, Dongyoon Han, Sung Ju Hwang
        link: https://openreview.net/forum?id=6VtAtwcrAH&referrer=%5BAuthor%20Console%5D(%2Fgroup%3Fid%3Dthecvf.com%2FCVPR%2F2023%2FConference%2FAuthors%23your-submissions)
        link_text: >
          [Paper]
      - layout: top-right
        title: Neural Architecture Search with Loss Flatness-aware Measure
        sub_title: ICMLW 2022 (DyNN Workshop)
        caption: <b>Joonhyun Jeong</b>, Joonsang Yu, Dongyoon Han, YoungJoon Yoo
        link: https://dynn-icml2022.github.io/papers/paper_11.pdf
        link_text: >
          [Paper]
      - layout: top-right
        title: Dataset Condensation via Efficient Synthetic-Data Parameterization
        sub_title: ICML 2022
        caption: Jang-Hyun Kim, Jinuk Kim, Seong Joon Oh, Sangdoo Yun, Hwanjun Song, <b>Joonhyun Jeong</b>, Jung-Woo Ha, Hyun Oh Song
        link: https://arxiv.org/abs/2205.14959
        link_text: >
          [Paper]
        additional_links:
          - title:  Code
            icon: fab fa-github
            url: https://github.com/snu-mllab/Efficient-Dataset-Condensation
      - layout: top-right
        title: Observations on K-image Expansion of Image-Mixing Augmentation for Classification
        sub_title: IEEE ACCESS 2023
        caption: <b>Joonhyun Jeong</b>, Sungmin Cha, Youngjoon Yoo, Sangdoo Yun, Taesup Moon, Jongwon Choi
        link: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10038702
        link_text: >
          [Paper]
        # additional_links:
        #   - title:  Code
        #     icon: fab fa-github
        #     url: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002567043
      - layout: top-right
        title: Bayesian Perspective on Visual Data Augmentation for Efficient Utilization of Subsampled Data
        sub_title: ICLRW 2021 (Synthetic Data Generation Workshop)
        caption: <b>Joonhyun Jeong</b>, Sungmin Cha, Youngjoon Yoo, Sangdoo Yun, Jongwon Choi
        link: https://sdg-quality-privacy-bias.github.io/papers/SDG_paper_10.pdf
        link_text: >
          [Paper]
        # additional_links:
        #   - title:  Code
        #     icon: fab fa-github
        #     url: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002567043
      - layout: top-right
        title: An Inter-Layer Weight Prediction and Quantization for Deep Neural Networks based on a Smoothly Varying Weight Hypothesis
        sub_title: Arxiv 2019
        caption: Kang-Ho Lee, <b>JoonHyun Jeong</b>, Sung-Ho Bae
        link: https://arxiv.org/abs/1907.06835
        link_text: >
          [Paper]
        # additional_links:
        #   - title:  Code
        #     icon: fab fa-github
        #     url: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002567043
      - layout: top-right
        title: A New Pointwise Convolution in Deep Neural Networks Through Extremely Fast and Non Parametric Transforms
        sub_title: IEEE ACCESS 2022
        caption: <b>Joonhyun Jeong</b>, Incheon Cho, Eunseop Shin, Sung-Ho Bae
        link: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9852205
        link_text: >
          [Paper]
        # additional_links:
        #   - title:  Code
        #     icon: fab fa-github
        #     url: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002567043
      - layout: top-right
        title: 고속 이산 코사인 변환을 이용한 새로운 경량화 콘볼루션 신경망
        sub_title: 2019 한국컴퓨터종합학술대회 (KCC2019), <b>우수논문상</b>
        caption: <b>Joonhyun Jeong</b>, Sung-Ho Bae
        link: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002567043
        link_text: >
          [Paper]
        # additional_links:
        #   - title:  Code
        #     icon: fab fa-github
        #     url: https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002567043
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: NAVER 1784 FaceSign 
        link: https://www.youtube.com/watch?v=uMPO9j06D7I&t=1s
        link_text: >
          [Youtube] FaceSign 개발 이야기
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Automatic Authentication System Based on Face Recognition. 
        description: | # this will include new lines to allow paragraphs
          I took a role of modeling part for Real-Time Face Detection & Facial Landmark Detection, aimed for extremely fast inference without accuracy performance degradation.
          \\
          <img src="/images/facesign.png" width="300px">
  - title: Talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Invited Talk from Naver Connect Foundation
        link: https://www.instagram.com/p/ChT1x1tBoi7/?utm_source=ig_web_copy_link
        link_text: >
          [Link]
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          Invited talk from Naver Connect Foundation, as a mentor for undergraduate students.
          \\
          <img src="/images/naverconnect.png" width="300px">
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Invited Lecture in Kyung-Hee University
        link: https://drive.google.com/file/d/1NAXx3wX3Z9LS-QkcGVU93nUpsejYF_2w/view?usp=sharing
        link_text: >
          [Video]
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          Invited lecture for career search seminar in Kyung-Hee University.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: KCC 2019 Oral Talk 
        link: https://www.youtube.com/watch?v=oxWYsFbrTao
        link_text: >
          [Youtube]
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          Invted talk for introducing the paper "A New Pointwise Convolution in Deep Neural Networks Through Extremely Fast and Non Parametric Transforms"
          \\
          <img src="/images/kcc_oral.png" width="300px">
  # - title: Talks
  #   KCCV
  #   경희대 진로탐색 세미나
  #   소프트웨어야 놀자
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
